const films = [
  {
    adult: false,
    backdrop_path: '/nLBRD7UPR6GjmWQp6ASAfCTaWKX.jpg',
    genre_ids: [16, 10751, 12, 14, 35],
    id: 502356,
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview:
      'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    popularity: 10702.084,
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    release_date: '2023-04-05',
    title: 'The Super Mario Bros. Movie',
    video: false,
    vote_average: 7.7,
    vote_count: 2875
  },
  {
    adult: false,
    backdrop_path: '/fI5RsaM0NSU6TqztRhA2pal5ezv.jpg',
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: 'en',
    original_title: 'Fast X',
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 5227.39,
    poster_path: '/1E5baAaEse26fej7uHcjOgEE2t2.jpg',
    release_date: '2023-05-17',
    title: 'Fast X',
    video: false,
    vote_average: 7.1,
    vote_count: 190
  },
  {
    adult: false,
    backdrop_path: '/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg',
    genre_ids: [53, 27, 14],
    id: 713704,
    original_language: 'en',
    original_title: 'Evil Dead Rise',
    overview:
      'Three siblings find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.',
    popularity: 4462.605,
    poster_path: '/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg',
    release_date: '2023-04-12',
    title: 'Evil Dead Rise',
    video: false,
    vote_average: 7.1,
    vote_count: 1157
  },
  {
    adult: false,
    backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
    genre_ids: [28, 12, 878],
    id: 640146,
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    popularity: 3897.568,
    poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
    release_date: '2023-02-15',
    title: 'Ant-Man and the Wasp: Quantumania',
    video: false,
    vote_average: 6.5,
    vote_count: 2694
  },
  {
    adult: false,
    backdrop_path: '/eTvN54pd83TrSEOz6wbsXEJktCV.jpg',
    genre_ids: [10752, 28, 53],
    id: 882569,
    original_language: 'en',
    original_title: "Guy Ritchie's The Covenant",
    overview:
      'During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.',
    popularity: 2791.731,
    poster_path: '/aX0H63vho7rZ9Rm3I567Zf00Z1t.jpg',
    release_date: '2023-04-19',
    title: "Guy Ritchie's The Covenant",
    video: false,
    vote_average: 7.8,
    vote_count: 230
  },
  {
    adult: false,
    backdrop_path: '/qElNES0sHVQcbzvGrTx7ccpGzij.jpg',
    genre_ids: [878, 28, 18],
    id: 842675,
    original_language: 'zh',
    original_title: '流浪地球2',
    overview: 'A prequel to The Wandering Earth.',
    popularity: 2768.256,
    poster_path: '/pR858ihc6Ls9xohpdRJVjV787ml.jpg',
    release_date: '2023-01-22',
    title: 'The Wandering Earth II',
    video: false,
    vote_average: 7.4,
    vote_count: 199
  },
  {
    adult: false,
    backdrop_path: '/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg',
    genre_ids: [27, 53, 14],
    id: 758323,
    original_language: 'en',
    original_title: "The Pope's Exorcist",
    overview:
      "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    popularity: 2414.356,
    poster_path: '/4IjRR2OW2itjQWQnmlUzvwLz9DQ.jpg',
    release_date: '2023-04-05',
    title: "The Pope's Exorcist",
    video: false,
    vote_average: 7.2,
    vote_count: 1063
  },
  {
    adult: false,
    backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
    genre_ids: [878, 12, 28],
    id: 447365,
    original_language: 'en',
    original_title: 'Guardians of the Galaxy Vol. 3',
    overview:
      'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
    popularity: 2020.805,
    poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    release_date: '2023-05-03',
    title: 'Guardians of the Galaxy Vol. 3',
    video: false,
    vote_average: 8.1,
    vote_count: 1364
  },
  {
    adult: false,
    backdrop_path: '/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg',
    genre_ids: [35, 28, 14],
    id: 594767,
    original_language: 'en',
    original_title: 'Shazam! Fury of the Gods',
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    popularity: 1991.492,
    poster_path: '/A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg',
    release_date: '2023-03-15',
    title: 'Shazam! Fury of the Gods',
    video: false,
    vote_average: 6.8,
    vote_count: 1645
  },
  {
    adult: false,
    backdrop_path: '/2w0YbYjtBfWdufOrWpsmrXCTl75.jpg',
    genre_ids: [28, 10752],
    id: 840326,
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    popularity: 1881.58,
    poster_path: '/pnQYjDxqZ3C6reI8N0MfNi4NMkZ.jpg',
    release_date: '2023-01-27',
    title: 'Sisu',
    video: false,
    vote_average: 6.9,
    vote_count: 156
  },
  {
    adult: false,
    backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    popularity: 1879.806,
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Way of Water',
    video: false,
    vote_average: 7.7,
    vote_count: 8070
  },
  {
    adult: false,
    backdrop_path: '/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg',
    genre_ids: [28, 35, 10749],
    id: 868759,
    original_language: 'en',
    original_title: 'Ghosted',
    overview:
      'Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.',
    popularity: 1744.906,
    poster_path: '/liLN69YgoovHVgmlHJ876PKi5Yi.jpg',
    release_date: '2023-04-18',
    title: 'Ghosted',
    video: false,
    vote_average: 7.1,
    vote_count: 828
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    genre_ids: [28, 53],
    id: 552688,
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    popularity: 1495.351,
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    release_date: '2023-05-04',
    title: 'The Mother',
    video: false,
    vote_average: 6.7,
    vote_count: 417
  },
  {
    adult: false,
    backdrop_path: '/7cra09dpSPto2jGZlK7OMbeO90O.jpg',
    genre_ids: [10749],
    id: 654374,
    original_language: 'ko',
    original_title: '막내 처제',
    overview:
      "One day, her family gathers for an offering and they worry that she's the only one without a boyfriend. Her brother-in-law, Ho-seok, sets her up on a blind date with his colleague, Min-soo, who has always been nice to him. The more she talks to Min-soo, the more Seo-ri realizes she is interested in her brother-in-law, Ho-seok. She then tries to meet up with him frequently.",
    popularity: 1483.843,
    poster_path: '/hC9yqXygRNVDz2B9NfZocqmhczM.jpg',
    release_date: '2019-12-08',
    title: 'The Youngest Sister-in-law',
    video: false,
    vote_average: 6,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: '/zPEDfWece7gg1I0904KFFVUq5mg.jpg',
    genre_ids: [53, 28, 80],
    id: 1102776,
    original_language: 'fr',
    original_title: 'AKA',
    overview:
      "A steely special ops agent finds his morality put to the test when he infiltrates a crime syndicate and unexpectedly bonds with the boss' young son.",
    popularity: 1428.11,
    poster_path: '/3BSxAjiporlwQTWzaHZ9Yrl5C9D.jpg',
    release_date: '2023-04-28',
    title: 'AKA',
    video: false,
    vote_average: 7,
    vote_count: 294
  },
  {
    adult: false,
    backdrop_path: '/e7FzphKs5gzoghDotAEp2FeP46u.jpg',
    genre_ids: [27, 35, 14],
    id: 649609,
    original_language: 'en',
    original_title: 'Renfield',
    overview:
      "Having grown sick and tired of his centuries as Dracula's lackey, Renfield finds a new lease on life — and maybe even redemption — when he falls for feisty, perennially angry traffic cop Rebecca Quincy.",
    popularity: 1423.32,
    poster_path: '/p6yUjhvNGQpFZilKwOKbxQ1eHlo.jpg',
    release_date: '2023-04-07',
    title: 'Renfield',
    video: false,
    vote_average: 7,
    vote_count: 436
  },
  {
    adult: false,
    backdrop_path: '/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg',
    genre_ids: [18, 28],
    id: 677179,
    original_language: 'en',
    original_title: 'Creed III',
    overview:
      'After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian — a fighter who has nothing to lose.',
    popularity: 1390.009,
    poster_path: '/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg',
    release_date: '2023-03-01',
    title: 'Creed III',
    video: false,
    vote_average: 7.3,
    vote_count: 1388
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    popularity: 1346.207,
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    release_date: '2023-03-22',
    title: 'John Wick: Chapter 4',
    video: false,
    vote_average: 7.9,
    vote_count: 1436
  },
  {
    adult: false,
    backdrop_path: '/w26FmegnHL8BykasYNHADIEURBW.jpg',
    genre_ids: [10752, 36, 28],
    id: 1037644,
    original_language: 'en',
    original_title: 'Battle for Saipan',
    overview:
      'On July 7, 1944, a U.S. Army hospital on the remote island of Saipan is overrun by Japanese forces during a relentless attack. Outgunned and surrounded by the enemy, a lone medic puts it all on the line to lead a band of wounded soldiers to safety.',
    popularity: 1218.895,
    poster_path: '/9N3KwhzBCcqmFcqHpPCsjqfym9M.jpg',
    release_date: '2022-11-25',
    title: 'Battle for Saipan',
    video: false,
    vote_average: 5.7,
    vote_count: 30
  },
  {
    adult: false,
    backdrop_path: '/44immBwzhDVyjn87b3x3l9mlhAD.jpg',
    genre_ids: [27, 9648, 53],
    id: 934433,
    original_language: 'en',
    original_title: 'Scream VI',
    overview:
      'Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.',
    popularity: 1161.447,
    poster_path: '/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg',
    release_date: '2023-03-08',
    title: 'Scream VI',
    video: false,
    vote_average: 7.3,
    vote_count: 1209
  },
  {
    adult: false,
    backdrop_path: '/3uHDuQCoJQ6DhRlI3frd7p9WSE2.jpg',
    genre_ids: [18, 35],
    id: 868985,
    original_language: 'es',
    original_title: '¡Que Viva México!',
    overview:
      "After his grandfather's death, a man travels with his wife and kids to his hometown, where chaos ensues with his relatives over the inheritance.",
    popularity: 1016.659,
    poster_path: '/ieyUpr5ES9QEz1cn4clCnBf9XJl.jpg',
    release_date: '2023-03-23',
    title: '¡Que Viva México!',
    video: false,
    vote_average: 7.5,
    vote_count: 63
  },
  {
    adult: false,
    backdrop_path: '/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg',
    genre_ids: [28, 12, 36, 18, 10752],
    id: 948713,
    original_language: 'en',
    original_title: 'The Last Kingdom: Seven Kings Must Die',
    overview:
      "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
    popularity: 975.371,
    poster_path: '/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg',
    release_date: '2023-04-14',
    title: 'The Last Kingdom: Seven Kings Must Die',
    video: false,
    vote_average: 7.3,
    vote_count: 371
  },
  {
    adult: false,
    backdrop_path: '/2rVkDZFLN6DI5PAoraoe9m4IRMN.jpg',
    genre_ids: [12, 14, 35],
    id: 493529,
    original_language: 'en',
    original_title: 'Dungeons & Dragons: Honor Among Thieves',
    overview:
      'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
    popularity: 943.946,
    poster_path: '/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg',
    release_date: '2023-03-23',
    title: 'Dungeons & Dragons: Honor Among Thieves',
    video: false,
    vote_average: 7.5,
    vote_count: 1306
  },
  {
    adult: false,
    backdrop_path: '/yx96Xz7ggs7TMmDqAa8G5oJ5ami.jpg',
    genre_ids: [37, 28],
    id: 1111140,
    original_language: 'en',
    original_title: 'Two Sinners and a Mule',
    overview:
      'Kicked out of a small Western town for sinful behavior, free-spirited Alice and Nora set out for Virginia City to pursue their dream of opening a restaurant. Out on the prairie, they come across an injured bounty hunter named Elden. Hoping to share in the reward, they nurse Elden back to health and help him stalk his prey, Grimes. But as Nora and Alice both develop feelings for Elden, no one notices that Grimes is now on their tail, and the hunters become the hunted…',
    popularity: 922.509,
    poster_path: '/icL1zn5z1L5ULIpxkuOLjeUgURY.jpg',
    release_date: '2023-04-21',
    title: 'Two Sinners and a Mule',
    video: false,
    vote_average: 6.2,
    vote_count: 16
  },
  {
    adult: false,
    backdrop_path: '/aRJjCgp4uVUkXhDw8NClesQXbt3.jpg',
    genre_ids: [53, 28],
    id: 727340,
    original_language: 'ko',
    original_title: '헌트',
    overview:
      'After a high-ranking North Korean official requests asylum, KCIA Foreign Unit chief Park Pyong-ho and Domestic Unit chief Kim Jung-do are tasked with uncovering a North Korean spy, known as Donglim, who is deeply embedded within their agency. When the spy begins leaking top secret intel that could jeopardize national security, the two units are each assigned to investigate each other.',
    popularity: 921.333,
    poster_path: '/tDe5eLxAbeK7sYckUn5aH3ngWnn.jpg',
    release_date: '2022-08-10',
    title: 'Hunt',
    video: false,
    vote_average: 6.9,
    vote_count: 79
  },
  {
    adult: false,
    backdrop_path: '/8HfjrSxfTVKmjNh8cJjbu5eXzcX.jpg',
    genre_ids: [10751, 14, 28, 12],
    id: 420808,
    original_language: 'en',
    original_title: 'Peter Pan & Wendy',
    overview:
      'Wendy Darling, a young girl afraid to leave her childhood home behind, meets Peter Pan, a boy who refuses to grow up. Alongside her brothers and a tiny fairy, Tinker Bell, she travels with Peter to the magical world of Neverland. There, she encounters an evil pirate captain, Captain Hook, and embarks on a thrilling adventure that will change her life forever.',
    popularity: 906.107,
    poster_path: '/8naZFKLQxhsYfvgveSP9Xw7Jv1B.jpg',
    release_date: '2023-04-20',
    title: 'Peter Pan & Wendy',
    video: false,
    vote_average: 5.8,
    vote_count: 361
  },
  {
    adult: false,
    backdrop_path: '/mfPfFVhpnGp8bG4IUoBJPUs2xKj.jpg',
    genre_ids: [878, 28, 12, 10751],
    id: 620705,
    original_language: 'en',
    original_title: 'Crater',
    overview:
      'After the death of his father, a boy growing up on a lunar mining colony takes a trip to explore a legendary crater, along with his four best friends, prior to being permanently relocated to another planet.',
    popularity: 898.278,
    poster_path: '/n8ZpMwYT02XjpQHpSxn1eJw5Zpz.jpg',
    release_date: '2023-05-12',
    title: 'Crater',
    video: false,
    vote_average: 6.7,
    vote_count: 85
  },
  {
    adult: false,
    backdrop_path: '/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
    genre_ids: [16, 10751, 14, 12, 35],
    id: 315162,
    original_language: 'en',
    original_title: 'Puss in Boots: The Last Wish',
    overview:
      'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
    popularity: 882.964,
    poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
    release_date: '2022-12-07',
    title: 'Puss in Boots: The Last Wish',
    video: false,
    vote_average: 8.3,
    vote_count: 5546
  },
  {
    adult: false,
    backdrop_path: '/bWZ4ge00FlDyHcOQZl7AzbZcrxT.jpg',
    genre_ids: [35, 28],
    id: 325358,
    original_language: 'en',
    original_title: 'Superfast!',
    overview:
      "Undercover cop Lucas White joins Vin Serento's LA gang of illegal street racers. They are fast and they are furious and they plan to double cross LA crime kingpin Juan Carlos de la Sol who hides his cash in a downtown Taco Bell. The gang's outrageous plan is as daring as it is ridiculous and will see them towing the whole restaurant, at crazy speeds.",
    popularity: 833.147,
    poster_path: '/iuIWl90qCpoxv6g775JB6Kg0m86.jpg',
    release_date: '2015-03-05',
    title: 'Superfast!',
    video: false,
    vote_average: 5,
    vote_count: 346
  },
  {
    adult: false,
    backdrop_path: '/wUwFMnbFxuDfcRSGGT7QQIGDRrH.jpg',
    genre_ids: [27],
    id: 785759,
    original_language: 'en',
    original_title: 'Two Witches',
    overview:
      'A matriarchal witch passes on her sinister inheritance to her grand-daughter, triggering the most horrific curses.',
    popularity: 806.155,
    poster_path: '/uL9fFTdNmUUlKIJfHJclN5X3bxH.jpg',
    release_date: '2023-03-02',
    title: 'Two Witches',
    video: false,
    vote_average: 6.5,
    vote_count: 52
  },
  {
    adult: false,
    backdrop_path: '/oGY415S8J0NxVbXKHaEOwns1ZWf.jpg',
    genre_ids: [28, 53],
    id: 507250,
    original_language: 'en',
    original_title: 'Dead Shot',
    overview:
      "In the 1970s, a member of the IRA takes over an Active Service Unit in London after his wife is accidentally shot dead in Ireland. The unit's mission is to cause chaos and destruction, while his personal aim is to hunt down his wife’s killer — an SAS captain, who is also hunting him.",
    popularity: 741.065,
    poster_path: '/s0Qx9YL1JSpYKm1hu0Ovj0IJ1SN.jpg',
    release_date: '2023-05-12',
    title: 'Dead Shot',
    video: false,
    vote_average: 7.3,
    vote_count: 12
  },
  {
    adult: false,
    backdrop_path: '/bT3IpP7OopgiVuy6HCPOWLuaFAd.jpg',
    genre_ids: [35, 80],
    id: 638974,
    original_language: 'en',
    original_title: 'Murder Mystery 2',
    overview:
      'After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.',
    popularity: 691.22,
    poster_path: '/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg',
    release_date: '2023-03-28',
    title: 'Murder Mystery 2',
    video: false,
    vote_average: 6.6,
    vote_count: 1055
  },
  {
    adult: false,
    backdrop_path: '/cYyUinLXRbQwE4PAt2mQLTGBqti.jpg',
    genre_ids: [28, 9648, 53],
    id: 876969,
    original_language: 'en',
    original_title: 'Assassin Club',
    overview:
      'In this world of contract killers, Morgan Gaines is the best of the best. When Morgan is hired to kill six people around the world, he soon discovers all the targets are also assassins unknowingly hired to kill each other.',
    popularity: 663.243,
    poster_path: '/y2d2SBqK33mGOG2CqAYMo3YbWE4.jpg',
    release_date: '2023-02-24',
    title: 'Assassin Club',
    video: false,
    vote_average: 6.7,
    vote_count: 55
  },
  {
    adult: false,
    backdrop_path: '/aT3sRVqgpkyCo23fp9myVfKPWbA.jpg',
    genre_ids: [18, 36],
    id: 964980,
    original_language: 'en',
    original_title: 'Air',
    overview:
      "Discover the game-changing partnership between a then undiscovered Michael Jordan and Nike's fledgling basketball division which revolutionized the world of sports and culture with the Air Jordan brand.",
    popularity: 618.349,
    poster_path: '/rdtgGyd1HEkODzm7he8TVlAwSob.jpg',
    release_date: '2023-04-05',
    title: 'Air',
    video: false,
    vote_average: 7.5,
    vote_count: 632
  },
  {
    adult: false,
    backdrop_path: '/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg',
    genre_ids: [28, 12, 35],
    id: 384018,
    original_language: 'en',
    original_title: 'Fast & Furious Presents: Hobbs & Shaw',
    overview:
      "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have traded smack talk and body blows. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, they join forces to defeat him.",
    popularity: 604.928,
    poster_path: '/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg',
    release_date: '2019-08-01',
    title: 'Fast & Furious Presents: Hobbs & Shaw',
    video: false,
    vote_average: 6.9,
    vote_count: 6344
  },
  {
    adult: false,
    backdrop_path: '/vL5zdAKAnbcHjoewXoP4xy6ihf7.jpg',
    genre_ids: [16, 10751, 878, 35],
    id: 1121116,
    original_language: 'en',
    original_title: 'Maggie Simpson in "Rogue Not Quite One"',
    overview:
      'On their way to daycare, Homer loses track of Maggie who hops in Grogu’s hovering pram for a hyperspace-hopping adventure across the galaxy. Facing a squadron of Imperial TIE fighters, Maggie brings the battle to Springfield in this epic short celebrating all things Star Wars.',
    popularity: 597.726,
    poster_path: '/gmTOhwzcSbEGG3xKRfQwwS2BTXD.jpg',
    release_date: '2023-05-04',
    title: 'Maggie Simpson in "Rogue Not Quite One"',
    video: false,
    vote_average: 5.2,
    vote_count: 15
  },
  {
    adult: false,
    backdrop_path: '/qUOJGvH8L31HL2b9Q6DGNPGCCI0.jpg',
    genre_ids: [53, 35, 80],
    id: 804150,
    original_language: 'en',
    original_title: 'Cocaine Bear',
    overview:
      'Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.',
    popularity: 596.658,
    poster_path: '/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg',
    release_date: '2023-02-22',
    title: 'Cocaine Bear',
    video: false,
    vote_average: 6.3,
    vote_count: 1054
  },
  {
    adult: false,
    backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
    genre_ids: [28, 12, 80, 53],
    id: 385128,
    original_language: 'en',
    original_title: 'F9',
    overview:
      "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    popularity: 580.705,
    poster_path: '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
    release_date: '2021-05-19',
    title: 'F9',
    video: false,
    vote_average: 7.2,
    vote_count: 6294
  },
  {
    adult: false,
    backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
    genre_ids: [28, 12, 878],
    id: 505642,
    original_language: 'en',
    original_title: 'Black Panther: Wakanda Forever',
    overview:
      'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
    popularity: 550.676,
    poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
    release_date: '2022-11-09',
    title: 'Black Panther: Wakanda Forever',
    video: false,
    vote_average: 7.3,
    vote_count: 4826
  },
  {
    adult: false,
    backdrop_path: '/eEF40Xk2twM3WjRNZftfo771gjv.jpg',
    genre_ids: [878, 12, 53],
    id: 700391,
    original_language: 'en',
    original_title: '65',
    overview:
      '65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.',
    popularity: 533.1,
    poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
    release_date: '2023-03-02',
    title: '65',
    video: false,
    vote_average: 6.3,
    vote_count: 1063
  },
  {
    adult: false,
    backdrop_path: '/ql4PnvKYKaMtdx9Ck4fHY2wJphT.jpg',
    genre_ids: [35, 18, 10749],
    id: 32516,
    original_language: 'cn',
    original_title: '金瓶梅2 愛的奴隸',
    overview:
      'Rich and powerful Simon Qing has been schooled in the ways of sex by his virile father, but is still a virgin. That is, until he meets his first love Violetta who has fun with him all over his father’s estate. Their love does not last, so Simon embarks on a journey. Along the way he meets the comely nun Moon whom Simon deflowers and then marries. He then becomes enamored of Golden Lotus but she is married to dwarf Wu Da-Lang.',
    popularity: 531.096,
    poster_path: '/A1yymig7S0FTWv9cTtOwdI1cH5V.jpg',
    release_date: '2009-03-04',
    title: 'The Forbidden Legend: Sex & Chopsticks 2',
    video: false,
    vote_average: 6.2,
    vote_count: 81
  },
  {
    adult: false,
    backdrop_path: '/pbMbDlOAkVuvnxovBA2ENin59xH.jpg',
    genre_ids: [12, 10751, 14, 10749],
    id: 447277,
    original_language: 'en',
    original_title: 'The Little Mermaid',
    overview:
      'The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.',
    popularity: 528.65,
    poster_path: '/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg',
    release_date: '2023-05-18',
    title: 'The Little Mermaid',
    video: false,
    vote_average: 6,
    vote_count: 24
  },
  {
    adult: false,
    backdrop_path: '/aityu1Gma509jInlspHstEt8Jg0.jpg',
    genre_ids: [12, 14, 10751],
    id: 736790,
    original_language: 'en',
    original_title: 'Chupa',
    overview:
      "While visiting family in Mexico, a lonely boy befriends a mythical creature hiding on his grandfather's ranch and embarks on the adventure of a lifetime.",
    popularity: 520.76,
    poster_path: '/ra3xm8KFAkwK0CdbPRkfYADJYTB.jpg',
    release_date: '2023-04-07',
    title: 'Chupa',
    video: false,
    vote_average: 6.5,
    vote_count: 229
  },
  {
    adult: false,
    backdrop_path: '/c3hl9E8E7b9opXDFVF5tSyk0ykr.jpg',
    genre_ids: [16, 35, 10751, 12, 14],
    id: 816904,
    original_language: 'es',
    original_title: 'Momias',
    overview:
      'Through a series of unfortunate events, three mummies end up in present-day London and embark on a wacky and hilarious journey in search of an old ring belonging to the Royal Family, stolen by ambitious archaeologist Lord Carnaby.',
    popularity: 496.244,
    poster_path: '/qVdrYN8qu7xUtsdEFeGiIVIaYd.jpg',
    release_date: '2023-01-05',
    title: 'Mummies',
    video: false,
    vote_average: 7.1,
    vote_count: 286
  },
  {
    adult: false,
    backdrop_path: '/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg',
    genre_ids: [28],
    id: 1048300,
    original_language: 'en',
    original_title: 'Adrenaline',
    overview:
      'A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.',
    popularity: 491.14,
    poster_path: '/mSgqZlz7umts77mEhmEhv9piUKv.jpg',
    release_date: '2022-12-15',
    title: 'Adrenaline',
    video: false,
    vote_average: 6,
    vote_count: 43
  },
  {
    adult: false,
    backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
    genre_ids: [28, 12, 878, 14],
    id: 436270,
    original_language: 'en',
    original_title: 'Black Adam',
    overview:
      'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
    popularity: 487.336,
    poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
    release_date: '2022-10-19',
    title: 'Black Adam',
    video: false,
    vote_average: 7.1,
    vote_count: 4908
  },
  {
    adult: false,
    backdrop_path: '/bF2skCyB5jeJuO26GFaQIGHrMNl.jpg',
    genre_ids: [27, 9648, 53],
    id: 1085103,
    original_language: 'en',
    original_title: 'Clock',
    overview:
      'On the eve of her 38th birthday, a woman desperately attempts to fix her broken biological clock.',
    popularity: 485.212,
    poster_path: '/m6Yt77C9u7Aume9dTJMCSRzWDED.jpg',
    release_date: '2023-03-28',
    title: 'Clock',
    video: false,
    vote_average: 5.9,
    vote_count: 81
  },
  {
    adult: false,
    backdrop_path: '/cZzZlwGvxiByXam0lZ57J9IN233.jpg',
    genre_ids: [27],
    id: 1008005,
    original_language: 'es',
    original_title: 'La niña de la comunión',
    overview:
      "Spain, late 1980s. Newcomer Sara tries to fit in with the other teens in this tight-knit small town in the province of Tarragona. If only she were more like her extroverted best friend, Rebe. They go out one night at a nightclub, on the way home, they come upon a little girl holding a doll, dressed for her first communion. And that's when the nightmare begins.",
    popularity: 478.412,
    poster_path: '/uYxrWr9o44yO0HvVfFFHGu01gfX.jpg',
    release_date: '2023-02-10',
    title: 'The Communion Girl',
    video: false,
    vote_average: 6.2,
    vote_count: 108
  },
  {
    adult: false,
    backdrop_path: '/f0nRX5F6VjzXMMzezZn48EQwjUn.jpg',
    genre_ids: [16],
    id: 579884,
    original_language: 'ru',
    original_title: 'Суворов: Великое путешествие',
    overview:
      'Sixteen-year-old servant Greg is in love with Sophia, the daughter of a wealthy merchant. The feeling is mutual but Sophia’s parents want her to marry another - a man of high social standing and low moral values. Greg is forcibly separated from his beloved and made to join General Alexander Suvorov’s army. During the legendary Swiss expedition, Greg earns the respect and loyalty of Suvorov and his men by thwarting a treacherous enemy plot, proving that anyone can be a hero if they are driven by love.',
    popularity: 464.653,
    poster_path: '/geZLtEgfuK7HMH9WcG2VuWtf9Gi.jpg',
    release_date: '2022-05-01',
    title: 'The Swiss Adventure',
    video: false,
    vote_average: 5.8,
    vote_count: 8
  },
  {
    adult: false,
    backdrop_path: '/tFaC1Fb1sv1dALB0i9Avi76MHmn.jpg',
    genre_ids: [10751, 28, 12],
    id: 946310,
    original_language: 'nl',
    original_title: "De Piraten van Hiernaast II: De Ninja's van de Overkant",
    overview:
      "The pirates feel right at home in Sandborough, but the atmosphere cools right down when the ninjas come to live in the street. After all, pirates and ninjas are sworn enemies!  While pirate captain Hector Blunderbuss struggles to get rid of his new neighbours, son Billy and ninja daughter Yuka become friends. The pirates challenge the ninjas to the ultimate battle at the village's annual hexathlon. Who will win the match? Ninjas are faster and more agile of course, but pirates are the best cheats in all of the seven seas...",
    popularity: 462.186,
    poster_path: '/uDsvma9dAwnDPVuCFi99YpWvBk0.jpg',
    release_date: '2022-04-20',
    title: 'Pirates Down the Street II: The Ninjas from Across',
    video: false,
    vote_average: 6.8,
    vote_count: 100
  },
  {
    adult: false,
    backdrop_path: '/eNJhWy7xFzR74SYaSJHqJZuroDm.jpg',
    genre_ids: [28, 878],
    id: 1033219,
    original_language: 'en',
    original_title: 'Attack on Titan',
    overview:
      "As viable water is depleted on Earth, a mission is sent to Saturn's moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don't trust that the Earthlings will leave in peace.",
    popularity: 461.263,
    poster_path: '/qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg',
    release_date: '2022-09-30',
    title: 'Attack on Titan',
    video: false,
    vote_average: 6,
    vote_count: 130
  },
  {
    adult: false,
    backdrop_path: '/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg',
    genre_ids: [27, 53],
    id: 980078,
    original_language: 'en',
    original_title: 'Winnie the Pooh: Blood and Honey',
    overview:
      'Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.',
    popularity: 456.712,
    poster_path: '/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg',
    release_date: '2023-01-27',
    title: 'Winnie the Pooh: Blood and Honey',
    video: false,
    vote_average: 5.7,
    vote_count: 589
  },
  {
    adult: false,
    backdrop_path: '/aJn9XeesqsrSLKcHfHP4u5985hn.jpg',
    genre_ids: [878, 12, 28, 35],
    id: 283995,
    original_language: 'en',
    original_title: 'Guardians of the Galaxy Vol. 2',
    overview:
      "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
    popularity: 454.141,
    poster_path: '/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg',
    release_date: '2017-04-19',
    title: 'Guardians of the Galaxy Vol. 2',
    video: false,
    vote_average: 7.6,
    vote_count: 19723
  },
  {
    adult: false,
    backdrop_path: '/ryQbb26wl1ggtypXiZW0kjKZCrP.jpg',
    genre_ids: [18, 12, 10749, 28, 36],
    id: 67308,
    original_language: 'cn',
    original_title: '3D肉蒲團之極樂寶鑑',
    overview:
      'Loosely based on a 17th century erotic Chinese story named The Carnal Prayer Mat, the story follows a young scholar named Yangsheng who gets married to the beautiful daughter of a local merchant. When their sex life proves unsatisfactory, Yangsheng leaves home and journeys to the Pavilion of Ultimate Bliss.',
    popularity: 439.149,
    poster_path: '/mmvFokJgpFmNt522Hfpq3Zfs2Ra.jpg',
    release_date: '2011-04-14',
    title: '3-D Sex and Zen: Extreme Ecstasy',
    video: false,
    vote_average: 4.9,
    vote_count: 93
  },
  {
    adult: false,
    backdrop_path: '/vgzHkWaj7HLCjizRzyO1Y0uE7e2.jpg',
    genre_ids: [16, 28, 14],
    id: 997776,
    original_language: 'en',
    original_title: 'Justice League x RWBY: Super Heroes & Huntsmen, Part One',
    overview:
      'Superman, Batman, Wonder Woman, Flash, Cyborg, Green Lantern and Vixen are transported to the strange world of Remnant and find themselves turned into teenagers. Meanwhile, Remnant heroes Ruby, Weiss, Blake and Yang must combine forces with the Justice League to uncover why their planet has been mysteriously altered before a superpowered Grimm destroys everything.',
    popularity: 435.834,
    poster_path: '/sjBFnG8DpouuWi161KbjbAER235.jpg',
    release_date: '2023-04-25',
    title: 'Justice League x RWBY: Super Heroes & Huntsmen, Part One',
    video: false,
    vote_average: 7.8,
    vote_count: 54
  },
  {
    adult: false,
    backdrop_path: '/43WkvO1EVTHz2rTlswdhmzjlNRF.jpg',
    genre_ids: [35],
    id: 1120558,
    original_language: 'es',
    original_title: 'Bendita Suegra',
    overview:
      'Andrea, a successful veterinarian who loves her job and is in a relationship with Lucio, an up-and-coming lawyer who grew up in the country. Lucio has some news for Andrea: his mother is turning 60 and is throwing a big party to celebrate. Andrea visits the town where Lucio was raised for the first time and would like to become very close to his family, especially her new Mother-in-law Blanca, who is an overprotective mother, ultra-conservative and always thinks she’s right about everything. Andrea tries to fit in by tolerating all her quirks and harsh treatment during the torturous weekend.',
    popularity: 431.163,
    poster_path: '/5xupm2thQic5GzYi6nim6URMZOY.jpg',
    release_date: '2023-05-10',
    title: 'Bendita Suegra',
    video: false,
    vote_average: 8,
    vote_count: 20
  },
  {
    adult: false,
    backdrop_path: '/yELOCXWN7mHpztKppR3ZLWG0CUp.jpg',
    genre_ids: [18, 10749],
    id: 1079078,
    original_language: 'no',
    original_title: 'Royalteen: Princess Margrethe',
    overview:
      "Last year’s prom ended in major drama for Princess Margrethe. She doesn’t dare tell anyone about what happened the night she was hospitalized. Suddenly the Danish royal family plans to visit Norway, and Princess Margrethe will finally get to meet the handsome Danish prince that she's been chatting with for months. As family drama starts piling up for the royal Norwegian family, she finds herself lost between taking care of her family, portraying herself as a strong princess, and being vulnerable in her quest for love.",
    popularity: 416.152,
    poster_path: '/2gkKRFDiuSvBB57glAMBsdRGeWk.jpg',
    release_date: '2023-05-11',
    title: 'Royalteen: Princess Margrethe',
    video: false,
    vote_average: 6.9,
    vote_count: 39
  },
  {
    adult: false,
    backdrop_path: '/tYcmm8XtzRdcT6kliCbHuWwLCwB.jpg',
    genre_ids: [28, 80, 53],
    id: 849869,
    original_language: 'ko',
    original_title: '길복순',
    overview:
      "At work, she's a renowned assassin. At home, she's a single mom to a teenage daughter. Killing? That's easy. It's parenting that's the hard part.",
    popularity: 413.329,
    poster_path: '/taYgn3RRpCGlTGdaGQvnSIOzXFy.jpg',
    release_date: '2023-02-17',
    title: 'Kill Boksoon',
    video: false,
    vote_average: 7,
    vote_count: 251
  },
  {
    adult: false,
    backdrop_path: '/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg',
    genre_ids: [28, 80, 53],
    id: 337339,
    original_language: 'en',
    original_title: 'The Fate of the Furious',
    overview:
      'When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.',
    popularity: 409.968,
    poster_path: '/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg',
    release_date: '2017-04-12',
    title: 'The Fate of the Furious',
    video: false,
    vote_average: 6.9,
    vote_count: 9466
  },
  {
    adult: false,
    backdrop_path: '/993utJnne28M1WNCIpk1uQQapfp.jpg',
    genre_ids: [14, 28, 12],
    id: 455476,
    original_language: 'en',
    original_title: 'Knights of the Zodiac',
    overview:
      'When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?',
    popularity: 398.622,
    poster_path: '/1nbFEdIFprRNSWcCM0RUjQqZifF.jpg',
    release_date: '2023-04-27',
    title: 'Knights of the Zodiac',
    video: false,
    vote_average: 6.5,
    vote_count: 46
  },
  {
    adult: false,
    backdrop_path: '/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg',
    genre_ids: [28, 12, 53],
    id: 646389,
    original_language: 'en',
    original_title: 'Plane',
    overview:
      'After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.',
    popularity: 396.644,
    poster_path: '/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg',
    release_date: '2023-01-12',
    title: 'Plane',
    video: false,
    vote_average: 6.9,
    vote_count: 1207
  },
  {
    adult: false,
    backdrop_path: '/6UQZkEA9WIj73LChP4wdPP9xHo6.jpg',
    genre_ids: [18],
    id: 747355,
    original_language: 'ko',
    original_title: '스와핑: 두 부부의 이혼여행',
    overview:
      "Yong-ho and Seong-ho decide to organize their marriage and leave the last memories. He decides to go on a trip to the sea where four people went together at the beginning of the wedding. In fact, they liked each other's opponents. In the open sea, each person begins to exude their hidden emotions...​",
    popularity: 385.47,
    poster_path: '/wESfP4ZeBbwjjFw2tql4Bqx101Q.jpg',
    release_date: '2020-08-28',
    title: 'Swapping: A Divorce Trip Between Two Couples',
    video: false,
    vote_average: 8.7,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: '/bPlmTl2rrnzgRKinLvs4GUd0DPb.jpg',
    genre_ids: [35],
    id: 1118721,
    original_language: 'es',
    original_title: 'Quiero Tu Vida',
    overview:
      "A former pro football player must retire after a life-altering injury, and as the years passes he wishes to know how his life would've turned out had he remained a star.",
    popularity: 382.844,
    poster_path: '/hk2kW6uwTEa8cxDeF1UPfIpEYkF.jpg',
    release_date: '2023-05-03',
    title: 'Quiero Tu Vida',
    video: false,
    vote_average: 6.5,
    vote_count: 24
  },
  {
    adult: false,
    backdrop_path: '/xmcPahH2mOkDAsIifOKoCacKhrw.jpg',
    genre_ids: [28],
    id: 842945,
    original_language: 'en',
    original_title: 'Supercell',
    overview:
      'Good-hearted teenager William always lived in hope of following in his late father’s footsteps and becoming a storm chaser. His father’s legacy has now been turned into a storm-chasing tourist business, managed by the greedy and reckless Zane Rogers, who is now using William as the main attraction to lead a group of unsuspecting adventurers deep into the eye of the most dangerous supercell ever seen.',
    popularity: 374.107,
    poster_path: '/gbGHezV6yrhua0KfAgwrknSOiIY.jpg',
    release_date: '2023-03-17',
    title: 'Supercell',
    video: false,
    vote_average: 6.2,
    vote_count: 153
  },
  {
    adult: false,
    backdrop_path: '/bblKpucB0XbyQBmfXsaRN985Rgh.jpg',
    genre_ids: [18],
    id: 458220,
    original_language: 'en',
    original_title: 'Palmer',
    overview:
      "After 12 years in prison, former high school football star Eddie Palmer returns home to put his life back together—and forms an unlikely bond with Sam, an outcast boy from a troubled home. But Eddie's past threatens to ruin his new life and family.",
    popularity: 370.562,
    poster_path: '/xSDdRAjxKAGi8fUBLOqSrBhJmF0.jpg',
    release_date: '2021-01-29',
    title: 'Palmer',
    video: false,
    vote_average: 8,
    vote_count: 983
  },
  {
    adult: false,
    backdrop_path: '/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg',
    genre_ids: [28, 53, 80],
    id: 168259,
    original_language: 'en',
    original_title: 'Furious 7',
    overview:
      'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.',
    popularity: 369.549,
    poster_path: '/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg',
    release_date: '2015-04-01',
    title: 'Furious 7',
    video: false,
    vote_average: 7.2,
    vote_count: 9721
  },
  {
    adult: false,
    backdrop_path: '/aHcWyh0n4YbBy9gxYCDlgsNVS3M.jpg',
    genre_ids: [27, 53],
    id: 631842,
    original_language: 'en',
    original_title: 'Knock at the Cabin',
    overview:
      'While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.',
    popularity: 368.543,
    poster_path: '/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg',
    release_date: '2023-02-01',
    title: 'Knock at the Cabin',
    video: false,
    vote_average: 6.4,
    vote_count: 1458
  },
  {
    adult: false,
    backdrop_path: '/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg',
    genre_ids: [878, 27, 35],
    id: 536554,
    original_language: 'en',
    original_title: 'M3GAN',
    overview:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    popularity: 366.515,
    poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
    release_date: '2022-12-28',
    title: 'M3GAN',
    video: false,
    vote_average: 7.3,
    vote_count: 2617
  },
  {
    adult: false,
    backdrop_path: '/koSIWq7ra4MAw5QBtbgs4kINKws.jpg',
    genre_ids: [10749, 35],
    id: 826942,
    original_language: 'en',
    original_title: 'Spin Me Round',
    overview:
      'When the manager of an Italian restaurant chain wins the opportunity to attend the franchise’s educational immersion program in Italy, what she thought would be a romantic getaway devolves into chaos and catastrophe.',
    popularity: 354.047,
    poster_path: '/oQ3EWU329YDGi4BOrEHpopq0BZi.jpg',
    release_date: '2022-08-19',
    title: 'Spin Me Round',
    video: false,
    vote_average: 4.9,
    vote_count: 51
  },
  {
    adult: false,
    backdrop_path: '/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg',
    genre_ids: [28, 35, 10749],
    id: 758009,
    original_language: 'en',
    original_title: 'Shotgun Wedding',
    overview:
      'Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.',
    popularity: 350.588,
    poster_path: '/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg',
    release_date: '2022-12-28',
    title: 'Shotgun Wedding',
    video: false,
    vote_average: 6.4,
    vote_count: 820
  },
  {
    adult: false,
    backdrop_path: '/rPSJAElGxOTko1zK6uIlYnTMFxN.jpg',
    genre_ids: [80],
    id: 1104040,
    original_language: 'en',
    original_title: 'Gangs of Lagos',
    overview:
      'A group of friends who each have to navigate their own destiny, growing up on the bustling streets and neighborhood of Isale Eko, Lagos.',
    popularity: 345.73,
    poster_path: '/nGwFsB6EXUCr21wzPgtP5juZPSv.jpg',
    release_date: '2023-04-07',
    title: 'Gangs of Lagos',
    video: false,
    vote_average: 6.3,
    vote_count: 39
  },
  {
    adult: false,
    backdrop_path: '/1PRWW60yQparK1I8Soyy9Evf7Dv.jpg',
    genre_ids: [16, 35, 10751, 18, 12],
    id: 869626,
    original_language: 'en',
    original_title: 'Marcel the Shell with Shoes On',
    overview:
      'Marcel is an adorable one-inch-tall shell who ekes out a colorful existence with his grandmother Connie and their pet lint, Alan. Once part of a sprawling community of shells, they now live alone as the sole survivors of a mysterious tragedy. But when a documentary filmmaker discovers them amongst the clutter of his Airbnb, the short film he posts online brings Marcel millions of passionate fans, as well as unprecedented dangers and a new hope at finding his long-lost family.',
    popularity: 345.082,
    poster_path: '/jaYmP4Ct8YLnxWAW2oYkUjeXtzm.jpg',
    release_date: '2022-06-24',
    title: 'Marcel the Shell with Shoes On',
    video: false,
    vote_average: 7.7,
    vote_count: 272
  },
  {
    adult: false,
    backdrop_path: '/5qlmAFORL49yTOPxhwBWABW2zm0.jpg',
    genre_ids: [27],
    id: 1105014,
    original_language: 'en',
    original_title: "Ripper's Revenge",
    overview:
      'One year on from the notorious Ripper murders, London is terrorised once again by a series of brutal killings. When gruesome letters from the Ripper begin landing on his desk, an innocent reporter finds himself drawn into a deadly mystery, threatening the lives of everyone around him.',
    popularity: 321.945,
    poster_path: '/cuEIBHTWAvaYkhhS8HfOkhce2MB.jpg',
    release_date: '2023-04-03',
    title: "Ripper's Revenge",
    video: false,
    vote_average: 5.9,
    vote_count: 21
  },
  {
    adult: false,
    backdrop_path: '/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg',
    genre_ids: [27, 14, 878, 53],
    id: 296271,
    original_language: 'en',
    original_title: 'The Devil Conspiracy',
    overview:
      'The hottest biotech company in the world has discovered they can clone history’s most influential people from the dead. Now, they are auctioning clones of Michelangelo, Galileo, Vivaldi, and others for tens of millions of dollars to the world’s ultra-rich. But when they steal the Shroud of Turin and clone the DNA of Jesus Christ, all hell breaks loose.',
    popularity: 320.768,
    poster_path: '/2lUYbD2C3XSuwqMUbDVDQuz9mqz.jpg',
    release_date: '2023-01-13',
    title: 'The Devil Conspiracy',
    video: false,
    vote_average: 6.4,
    vote_count: 159
  },
  {
    adult: false,
    backdrop_path: '/2Eewgp7o5AU1xCataDmiIL2nYxd.jpg',
    genre_ids: [18, 36],
    id: 943822,
    original_language: 'en',
    original_title: 'Prizefighter: The Life of Jem Belcher',
    overview:
      'At the turn of the 19th century, Pugilism was the sport of kings and a gifted young boxer fought his way to becoming champion of England.',
    popularity: 319.375,
    poster_path: '/x3PIk93PTbxT88ohfeb26L1VpZw.jpg',
    release_date: '2022-06-30',
    title: 'Prizefighter: The Life of Jem Belcher',
    video: false,
    vote_average: 6.2,
    vote_count: 127
  },
  {
    adult: false,
    backdrop_path: '/g03h9TULzJZOoXA34Abp5LE7lvt.jpg',
    genre_ids: [16, 14, 12],
    id: 876792,
    original_language: 'ja',
    original_title: '劇場版 転生したらスライムだった件 紅蓮の絆編',
    overview:
      'A long-running conspiracy is swirling over a mysterious power wielded by the Queen in Raja, a small country west of Tempest. When a slime who evolved into a Demon Lord named Rimuru Tempest crosses paths with Hiiro, a survivor of the Ogre race, an incredible adventure packed with new characters begins. The power of bonds will be put to the test!',
    popularity: 317.542,
    poster_path: '/xITip9n9uMAUA0TU6niMXU2tbh0.jpg',
    release_date: '2022-11-25',
    title: 'That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond',
    video: false,
    vote_average: 7.7,
    vote_count: 205
  },
  {
    adult: false,
    backdrop_path: '/cevmHkKqSlrTYqpJ5eaAjml1jec.jpg',
    genre_ids: [28, 18, 27, 878, 53],
    id: 1084225,
    original_language: 'en',
    original_title: 'The Park',
    overview:
      'A dystopian coming-of-age movie focused on three kids who find themselves in an abandoned amusement park, aiming to unite whoever remains. With dangers lurking around every corner, they will do whatever it takes to survive their hellish Neverland.',
    popularity: 317.326,
    poster_path: '/hR1jdCw0A9czgsbp45TASkjjBhA.jpg',
    release_date: '2023-03-02',
    title: 'The Park',
    video: false,
    vote_average: 5.9,
    vote_count: 43
  },
  {
    adult: false,
    backdrop_path: '/bKWFetR4injOJXOGHeLuTD7wHI4.jpg',
    genre_ids: [27, 53, 14],
    id: 994128,
    original_language: 'es',
    original_title: 'Viejos',
    overview:
      'An octogenarian named Manuel falls into a state of dementia after the sudden suicide of his wife, sparking a series of paranormal events that will put his family’s lives at risk.',
    popularity: 307.746,
    poster_path: '/88f35mGJOIE1nXgst5o4FvEDVzr.jpg',
    release_date: '2023-04-21',
    title: 'The Elderly',
    video: false,
    vote_average: 7.4,
    vote_count: 14
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 80, 53],
    id: 730629,
    original_language: 'en',
    original_title: 'John Wick: Chapter 5',
    overview: 'The fifth installment in the John Wick franchise, confirmed to be in development.',
    popularity: 299.814,
    poster_path: '/A1Z4TjH3xqu4rHwAgLM3LX89luC.jpg',
    title: 'John Wick: Chapter 5',
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: '/70aVSo3fuZ94jyQ3rT64afEf8lV.jpg',
    genre_ids: [16, 12, 35, 10751, 14],
    id: 676710,
    original_language: 'en',
    original_title: 'The Amazing Maurice',
    overview:
      'Maurice is a streetwise ginger cat who comes up with a money-making scam by befriending a group of self-taught talking rats. When Maurice and the rodents meet a bookworm called Malicia, their little con soon goes down the drain.',
    popularity: 294.153,
    poster_path: '/ydhZeUjbzVEFclUpMhLfDZSavUY.jpg',
    release_date: '2022-12-16',
    title: 'The Amazing Maurice',
    video: false,
    vote_average: 7.1,
    vote_count: 77
  },
  {
    adult: false,
    backdrop_path: '/aVPR4EScBkSgznEy0TixQk8z4Ny.jpg',
    genre_ids: [53, 9648, 18, 27],
    id: 1114905,
    original_language: 'es',
    original_title: 'Uno para morir',
    overview:
      'Seven strangers wake up in a mansion in the middle of nowhere to discover they are part of a twisted game. They will have 60 minutes to choose one person to die; otherwise, all of them will be murdered. As the clock ticks down, the most lurid secrets will come to light, and they’ll discover they are all connected by a dark past.',
    popularity: 286.135,
    poster_path: '/yMeKoe3ui4Pad8FUOJwCby3SOWe.jpg',
    release_date: '2023-05-05',
    title: "Death's Roulette",
    video: false,
    vote_average: 6.5,
    vote_count: 89
  },
  {
    adult: false,
    backdrop_path: '/hlxduUs8y9icWGMzYCDLcYHEQ2u.jpg',
    genre_ids: [53],
    id: 985939,
    original_language: 'en',
    original_title: 'Fall',
    overview:
      'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights',
    popularity: 285.398,
    poster_path: '/v28T5F1IygM8vXWZIycfNEm3xcL.jpg',
    release_date: '2022-08-11',
    title: 'Fall',
    video: false,
    vote_average: 7.3,
    vote_count: 2868
  },
  {
    adult: false,
    backdrop_path: '/cvOpdYUIk3elPdOk7Y5esBzKeM.jpg',
    genre_ids: [16, 35],
    id: 650270,
    original_language: 'ja',
    original_title: 'リョーマ！The Prince of Tennis 新生劇場版テニスの王子様',
    overview:
      'Inspired by his tennis champion father, Ryoma is determined to take his game to the next level and train in the US. But in the middle of an intense tennis battle to save his classmate Sakuno from dangerous villains, they somehow find themselves transported back to the past, just as Ryoma’s father is about to undertake his final championship match at the US Open – when he was mysteriously forced to retire.',
    popularity: 285.123,
    poster_path: '/c2vONcT7dvhwtyhPbighDLWpZHJ.jpg',
    release_date: '2021-11-11',
    title: 'Ryoma! The Prince of Tennis',
    video: false,
    vote_average: 4,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: '/Xfn9eDOaZKSz5W3PRoJI928I9c.jpg',
    genre_ids: [28, 12, 36, 18],
    id: 875104,
    original_language: 'zh',
    original_title: '叶问宗师觉醒',
    overview:
      "When a young Master Ip stops a kidnapping, he ignites a turf war with a ruthless human-trafficking ring. In retaliation, the gang kidnaps one of Ip Man's close friends, forcing him to face the group's brutal boxing champion head-on.",
    popularity: 281.539,
    poster_path: '/A7vhdyGrpPMKXsuFBZzxmave94F.jpg',
    release_date: '2023-05-05',
    title: 'Ip Man: The Awakening',
    video: false,
    vote_average: 6.1,
    vote_count: 9
  },
  {
    adult: false,
    backdrop_path: '/AsEgGeccI32SwMBkxpwhOkhbzmF.jpg',
    genre_ids: [28, 878, 53, 27],
    id: 1011679,
    original_language: 'en',
    original_title: 'Shark Side of the Moon',
    overview:
      'Decades ago, the USSR developed unkillable sharks and launched them to the moon. Today, a team of American astronauts will endure the fight of their lives.',
    popularity: 281.271,
    poster_path: '/v5CfpzxoJDkZxjZAizClFdlEF0U.jpg',
    release_date: '2022-08-12',
    title: 'Shark Side of the Moon',
    video: false,
    vote_average: 5.3,
    vote_count: 124
  },
  {
    adult: false,
    backdrop_path: '/ceYZCBfwbBwSpGJ6PapNVw5jqLG.jpg',
    genre_ids: [16, 18, 12, 14],
    id: 916224,
    original_language: 'ja',
    original_title: 'すずめの戸締まり',
    overview:
      'Suzume, 17, lost her mother as a little girl. On her way to school, she meets a mysterious young man. But her curiosity unleashes a calamity that endangers the entire population of Japan, and so Suzume embarks on a journey to set things right.',
    popularity: 280.027,
    poster_path: '/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg',
    release_date: '2022-11-11',
    title: 'Suzume',
    video: false,
    vote_average: 7.9,
    vote_count: 377
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [53],
    id: 1076605,
    original_language: 'es',
    original_title: 'Cazadora',
    overview:
      'In a dystopian future, a mother and her teenage son go hunting in the mountains and encounter a stranger who threatens to upend their relationship.',
    popularity: 279.961,
    poster_path: '/8QxCd3pSSrj6QqaG4fkNkaJmUa.jpg',
    release_date: '2023-01-19',
    title: 'Cazadora',
    video: false,
    vote_average: 6.1,
    vote_count: 20
  },
  {
    adult: false,
    backdrop_path: '/ynpefecsZumBA37vXXaBHK3giln.jpg',
    genre_ids: [16, 10751, 878, 14],
    id: 265712,
    original_language: 'ja',
    original_title: 'STAND BY ME ドラえもん',
    overview:
      'Sewashi and Doraemon find themselves way back in time and meet Nobita. It is up to Doraemon to take care of Nobita or else he will not return to the present.',
    popularity: 279.742,
    poster_path: '/wc7XQbfx6EIQqCuvmBMt3aisb2Y.jpg',
    release_date: '2014-08-08',
    title: 'Stand by Me Doraemon',
    video: false,
    vote_average: 7.3,
    vote_count: 429
  },
  {
    adult: false,
    backdrop_path: '/u5nY7pY2Y58o7dSM9cy6NclOV8V.jpg',
    genre_ids: [27],
    id: 1023313,
    original_language: 'es',
    original_title: 'La Exorcista',
    overview:
      "Ophelia, a young nun recently arriving in the town of San Ramon, is forced to perform an exorcism on a pregnant woman in danger of dying. Just when she thinks her possession has ended, she discovers that the evil presence hasn't disappeared yet. The director of the award-winning Here Comes the Devil and Late Phases adds a new twist to possession movies in one of this year's Latin American horror surprises.",
    popularity: 278.981,
    poster_path: '/d07xtqwq1uriQ1hda6qeu8Skt5m.jpg',
    release_date: '2022-11-02',
    title: 'The Exorcist',
    video: false,
    vote_average: 5.9,
    vote_count: 80
  },
  {
    adult: false,
    backdrop_path: '/rH3jY9JN9krUyE0Q3WLNtujMs8.jpg',
    genre_ids: [28, 12, 878],
    id: 667538,
    original_language: 'en',
    original_title: 'Transformers: Rise of the Beasts',
    overview:
      "A '90s globetrotting adventure that introduces the Maximals, Predacons, and Terrorcons to the existing battle on earth between Autobots and Decepticons.",
    popularity: 275.439,
    poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
    release_date: '2023-06-06',
    title: 'Transformers: Rise of the Beasts',
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: '/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
    genre_ids: [28, 18],
    id: 361743,
    original_language: 'en',
    original_title: 'Top Gun: Maverick',
    overview:
      'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
    popularity: 271.334,
    poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    release_date: '2022-05-24',
    title: 'Top Gun: Maverick',
    video: false,
    vote_average: 8.3,
    vote_count: 6831
  },
  {
    adult: false,
    backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: 'en',
    original_title: 'Spider-Man: No Way Home',
    overview:
      'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    popularity: 263.814,
    poster_path: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
    release_date: '2021-12-15',
    title: 'Spider-Man: No Way Home',
    video: false,
    vote_average: 8,
    vote_count: 17365
  },
  {
    adult: false,
    backdrop_path: '/4B6bYj7gr5wQBvQQhDwr6tzJyGR.jpg',
    genre_ids: [10752, 28, 18],
    id: 966220,
    original_language: 'uk',
    original_title: 'Снайпер. Білий ворон',
    overview:
      'Mykola is an eccentric pacifist who wants to be useful to humanity. When the war begins at Donbass, Mykola’s naive world is collapsing as the militants kill his pregnant wife and burn his home to the ground. Recovered, he makes a cardinal decision and gets enlisted in a sniper company. Having met his wife’s killers, he emotionally breaks down and arranges “sniper terror” for the enemy. He’s saved from a senseless death by his instructor who himself gets mortally wounded. The death of a friend leaves a “scar” and Mykola is ready to sacrifice his life.',
    popularity: 254.719,
    poster_path: '/295gZzTXMvuiIG0U19h4M44PXxI.jpg',
    release_date: '2022-05-03',
    title: 'Sniper: The White Raven',
    video: false,
    vote_average: 7.5,
    vote_count: 377
  },
  {
    adult: false,
    backdrop_path: '/vFJ208yMK5rWoJ1aBy1Q1AsXzVp.jpg',
    genre_ids: [10749],
    id: 701952,
    original_language: 'ko',
    original_title: '여친 엄마2',
    overview:
      "Young Se-hee gets married to middle aged Min-goo, but she's not happy with his 'item' as he's old. While she goes on vacation with her husband, Min-goo's daughter Yoo-jin calls her boyfriend Ji-hoon to the house when her parents are not there and they have sex. Meanwhile, Se-hee comes back home early from the vacation because her husband has to work and runs into a completely naked Ji-hoon.",
    popularity: 253.956,
    poster_path: '/5OMeVCF5jZpCrrvJNEMMP0vOoIH.jpg',
    release_date: '2018-08-30',
    title: "My Girlfriend's Mother 2",
    video: false,
    vote_average: 2.2,
    vote_count: 5
  },
  {
    adult: false,
    backdrop_path: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
    genre_ids: [14, 28, 35],
    id: 616037,
    original_language: 'en',
    original_title: 'Thor: Love and Thunder',
    overview:
      'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
    popularity: 250.864,
    poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
    release_date: '2022-07-06',
    title: 'Thor: Love and Thunder',
    video: false,
    vote_average: 6.6,
    vote_count: 5959
  },
  {
    adult: false,
    backdrop_path: '/hT9ZUwLN5tB2O7miBu1oIMJFqJT.jpg',
    genre_ids: [12, 28, 878],
    id: 507086,
    original_language: 'en',
    original_title: 'Jurassic World Dominion',
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators ona planet they now share with history's most fearsome creatures.",
    popularity: 250.236,
    poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
    release_date: '2022-06-01',
    title: 'Jurassic World Dominion',
    video: false,
    vote_average: 6.9,
    vote_count: 4819
  },
  {
    adult: false,
    backdrop_path: '/odbZxn4qPWqCdTU5EZw4324k8Rq.jpg',
    genre_ids: [18],
    id: 829503,
    original_language: 'en',
    original_title: 'Gigi & Nate',
    overview:
      'A young man with a bright future suffers a near-fatal accident and recreates his new life with the help of an unlikely animal friend.',
    popularity: 249.47,
    poster_path: '/xP1GXV1gms9b5BpHZP7S8qs8FO.jpg',
    release_date: '2022-09-02',
    title: 'Gigi & Nate',
    video: false,
    vote_average: 8.2,
    vote_count: 43
  },
  {
    adult: false,
    backdrop_path: '/7eccX0xay9pDj6ZQvU4cu3whw18.jpg',
    genre_ids: [16, 14, 27, 28, 9648],
    id: 1003579,
    original_language: 'en',
    original_title: 'Batman: The Doom That Came to Gotham',
    overview:
      "Explorer Bruce Wayne accidentally unleashes an ancient evil, and returns to Gotham after being away for two decades. There, Batman battles Lovecraftian supernatural forces and encounters allies and enemies such as Green Arrow, Ra's al Ghul, Mr. Freeze, Killer Croc, Two-Face and James Gordon.",
    popularity: 246.212,
    poster_path: '/hrATQE8ScQceohwInaMluluNEaf.jpg',
    release_date: '2023-03-10',
    title: 'Batman: The Doom That Came to Gotham',
    video: false,
    vote_average: 6.5,
    vote_count: 86
  },
  {
    adult: false,
    backdrop_path: '/yEQqrW61rwNuVRHTjgHOAU4dXNE.jpg',
    genre_ids: [28, 12, 10751, 35],
    id: 675353,
    original_language: 'en',
    original_title: 'Sonic the Hedgehog 2',
    overview:
      'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
    popularity: 241.498,
    poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
    release_date: '2022-04-08',
    title: 'Sonic the Hedgehog 2',
    video: false,
    vote_average: 7.6,
    vote_count: 3920
  },
  {
    adult: false,
    backdrop_path: '/afsYFdid9pnnRd6tTrHFUbHgXJn.jpg',
    genre_ids: [878],
    id: 843794,
    original_language: 'ko',
    original_title: '정이',
    overview:
      'On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.',
    popularity: 237.229,
    poster_path: '/z2nfRxZCGFgAnVhb9pZO87TyTX5.jpg',
    release_date: '2023-01-20',
    title: 'JUNG_E',
    video: false,
    vote_average: 6.3,
    vote_count: 456
  }
]
export default films
